export * from './contentblock.fake'
export * from './footer.fake'
export * from './imageWithTextData.fake'
export * from './insta.fake'
export * from './Map.fake'
export * from './slider.fake'
export * from './timetable.fake'
